# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Invoke Azure Load Testing
# Run an Apache JMeter test script in Azure Load Testing
- task: AzureLoadTest@1
  inputs:
    azureSubscription: 'POC_Connection'
    loadTestConfigFile: 'Test_6/21/2022_12:51:05PM'
    resourceGroup: 'POC_ResourceGroup'
    loadTestResource: 'POC_InstanceName'
    #secrets:               # Optional. Array of JSON objects that consist of the name and value for each secret. The name should match the secret name used in the Apache JMeter test script.
    #env:                   # Optional. Array of JSON objects that consist of the name and value for each environment variable. The name should match the variable name used in the Apache JMeter test script.